server:
  port: 51602
spring:
  rabbitmq:
    host: 14.29.181.103
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
      direct:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 3000
        default-requeue-rejected: false
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  application:
    #应用的名称，可选
    name: huahuo-book
  cache:
    redis:
      time-to-live: 1800000
  datasource:
    druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://14.29.181.103:3308/huahuo_book?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 20030416cjh





#
#  redis:
#    host: tycloud.fzuhuahuo.cn
#    port: 6379
#    #password: 123456
#    database: 0 #操作的是0号数据库
#    jedis:
#      #Redis连接池配置
#      pool:
#        max-active: 8 #最大连接数
#        max-wait: 1ms #连接池最大阻塞等待时间
#        max-idle: 4 #连接池中的最大空闲连接
#        min-idle: 0 #连接池中的最小空闲连接


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

